[[redirects]]
  from = "/api/*"
  to = "https://inventory-app-01.onrender.com/:splat"
  status = 200
  force = true

# Additional redirects or settings can be added below
# ...

# Example: Redirect other routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
